name: Update Fork

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday
  workflow_dispatch:

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: <your-username>/<theme-repo>
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/<original-owner>/<theme-repo>.git
          git fetch upstream
          git merge upstream/main
          git push origin main
